framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        # Memcached
        app: cache.adapter.memcached
        default_memcached_provider: 'memcached://localhost:11211'

        # Namespaced pools use the above "app" backend by default
        pools:
            # uses the default_memcached_provider from above
            app.cache.jobs:
                adapter: cache.adapter.memcached
                public: false
                default_lifetime: 300  # 5 minutes
            doctrine.metadata_cache_pool:
                adapter: cache.adapter.memcached
            doctrine.query_cache_pool:
                adapter: cache.adapter.memcached
            doctrine.result_cache_pool:
                adapter: cache.adapter.memcached
